### ISSUE TITLE
404 resource not found

### ISSUE THREAD

**Issue by pervez8ktt** [surdocteam/gwlib#1]
Hi
when I tried to run 
<code>wget https://github.com/surdocteam/gwlib/releases/download/v1.0.1-beta.3/release-v1.0.1-beta.3.zip -O release-v1.0.1-beta.3.zip</code>

my console shows 404 resource not found please provide me update

i am using this link https://github.com/surdocteam/gwlib/blob/master/doc/how-run-gateway.md
thanks

**Comment by MoZhonghua** [comment]
please download the lastest version from release pages:

https://github.com/surdocteam/gwlib/releases

**Comment by pervez8ktt** [comment]
thanks :)
